# 17. Strojové učení - Příprava dat, Chyby v datech a bias, Korelace a kauzalita

### Příprava dat
* Data samotná jsou jen zaznamenané údaje
* Informací se data stávají až dodáním kontextu a významu
* Pro strojové učení je dělíme na:
    * Strukturovaná: Počítačem snadno zpracovatelná, jasná struktura (např. relační databáze nebo CSV soubory)
    * Nestrukturovaná: Pro člověka srozumitelná, pro počítač složitější (např. obrázky, videa, volný text)
* Data se získávají měřením (senzory), průzkumy, ruční tvorbou nebo generováním

### Reprezentativita a šum
* Pokud máme dat málo nebo neodpovídají zkoumanému problému, nejsou reprezentativní a nelze z nich vyvozovat závěry
* Šum je náhodná chyba vyskytující se v datech, pokud není příliš výrazný tak většině algoritmů nevadí

### Bias
* Narozdíl od šumu je bias systematická chyba
* Ta je velmi nebezpečná, protože přímo a výrazně ovlivňuje globální statistiky
* Způsobuje ji např. výběrové zkreslení, typicky třeba počítání průměrné mzdy v ČR z datového vzorku, ve kterém jsou jen absolventi vysokých škol žijících v Praze

### Korelace a kauzalita
* Problémem při interpretaci dat je záměna těchto dvou pojmů
* Korelace vyjadřuje statistickou závislost mezi dvěma veličinami, např. podle dat platí, že vysoký výskyt žížal na zahradě silně koreluje s vysokým výskytem slimáků
* Kauzalita je příčinná souvislost, kde jedna událost přímo způsobuje druhou, např. výskyt žížal nezpůsobuje výskyt slimáků a naopak, společnou příčinou je deštivé počasí
* Model strojového učení najde korelaci, kauzalitu musí pohlídat datový vědec

**1. Data s chybami**

In [3]:
import pandas as pd

data = {
    "model": ["Superb", "Superb", "Octavia", "Fabia"],
    "rok_vyroby": [2017, 2017, 2019, 2010],
    "palivo": ["Diesel", "Diesel", "Benzín", None], # Chybějící hodnota (None)
    "najeto_mil": [30000, -500, 120000, 90000],     # -500 je nesmysl (chyba)
    "cena_libry": [15000, 15200, 11000, 3000]
}
df = pd.DataFrame(data)
df

     model  rok_vyroby  palivo  najeto_mil  cena_libry
0   Superb        2017  Diesel       30000       15000
1   Superb        2017  Diesel        -500       15200
2  Octavia        2019  Benzín      120000       11000
3    Fabia        2010     NaN       90000        3000

**2. Příprava dat a oprava**

In [4]:
df = df[df["najeto_mil"] >= 0]
df["palivo"] = df["palivo"].fillna("Nezname")

df_ready = pd.get_dummies(df, columns=["model", "palivo"])
df_ready

,rok_vyroby,najeto_mil,cena_libry,model_Fabia,model_Octavia,model_Superb,palivo_Benzín,palivo_Diesel,palivo_Nezname
0,2017,30000,15000,False,False,True,False,True,False
2,2019,120000,11000,False,True,False,True,False,False
3,2010,90000,3000,True,False,False,False,False,True